# Generated by Django 4.2.7 on 2023-11-05 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swarmName', models.CharField(max_length=32, unique=True)),
                ('createdAt', models.DateTimeField(verbose_name='datePublished')),
                ('UpdatedAt', models.DateTimeField(verbose_name='dateUpdated')),
                ('UpdatedBy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droneName', models.CharField(max_length=32, unique=True)),
                ('MAC_Address', models.CharField(max_length=17)),
                ('IPAddress', models.GenericIPAddressField()),
                ('createdAT', models.DateTimeField(verbose_name='datePublished')),
                ('updatedBy', models.IntegerField()),
                ('swarmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.swarm')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
