# Generated by Django 4.2.7 on 2023-11-12 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dateJoined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='lastLogin')),
                ('is_super_user', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSID', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(default='1234', max_length=32)),
                ('AuthMethod', models.CharField(default='EAP', max_length=16)),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datePublished')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='dateUpdated')),
                ('UpdatedBy', models.CharField(default='User', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swarmName', models.CharField(max_length=32, unique=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datePublished')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='dateUpdated')),
                ('UpdatedBy', models.CharField(default='User', max_length=32)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droneName', models.CharField(max_length=32, unique=True)),
                ('MAC_Address', models.CharField(default='00-00-00-00-00-00', max_length=17)),
                ('IPAddress', models.GenericIPAddressField(default='192.168.1.1')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datePublished')),
                ('UpdatedBy', models.CharField(default='User', max_length=32)),
                ('swarm_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.swarm')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
