# Generated by Django 4.2.7 on 2023-11-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='IPAddress',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='MAC_Address',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='createdAT',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='swarmID',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='updatedBy',
        ),
    ]
