# Generated by Django 4.2.7 on 2023-11-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_drone_ipaddress_remove_drone_mac_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='swarm',
            name='UpdatedAt',
        ),
        migrations.RemoveField(
            model_name='swarm',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='swarm',
            name='createdAt',
        ),
    ]
