# Generated by Django 4.2.7 on 2023-11-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_drone_userid_remove_swarm_updatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
    ]
