# Generated by Django 4.2.7 on 2023-11-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_drone_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='swarm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.swarm'),
        ),
    ]
