# Generated by Django 4.2.7 on 2023-11-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_drone_swarm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='swarm_id',
        ),
    ]
