# Generated by Django 4.2.7 on 2023-11-07 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_drone_swarm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='IPAddress',
            field=models.GenericIPAddressField(default='192.168.1.1'),
        ),
        migrations.AddField(
            model_name='drone',
            name='MAC_Address',
            field=models.CharField(default='00-00-00-00-00-00', max_length=17),
        ),
        migrations.AddField(
            model_name='drone',
            name='createdAT',
            field=models.DateTimeField(default=None, verbose_name='datePublished'),
        ),
        migrations.AddField(
            model_name='drone',
            name='swarm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.swarm'),
        ),
        migrations.AddField(
            model_name='drone',
            name='updatedBy',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='swarm',
            name='UpdatedAt',
            field=models.DateTimeField(default=None, verbose_name='dateUpdated'),
        ),
        migrations.AddField(
            model_name='swarm',
            name='UpdatedBy',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='swarm',
            name='createdAt',
            field=models.DateTimeField(default=None, verbose_name='datePublished'),
        ),
    ]
