# Generated by Django 4.2.7 on 2023-11-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_drone_ipaddress_drone_mac_address_drone_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='updatedBy',
            field=models.IntegerField(default=' '),
        ),
        migrations.AlterField(
            model_name='swarm',
            name='UpdatedBy',
            field=models.IntegerField(default=' '),
        ),
    ]
