# Generated by Django 4.2.7 on 2023-11-07 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_drone_updatedby_alter_swarm_updatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='createdAT',
            field=models.DateTimeField(default=datetime.datetime, verbose_name='datePublished'),
        ),
        migrations.AlterField(
            model_name='swarm',
            name='UpdatedAt',
            field=models.DateTimeField(default=datetime.datetime, verbose_name='dateUpdated'),
        ),
        migrations.AlterField(
            model_name='swarm',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime, verbose_name='datePublished'),
        ),
    ]
