# Generated by Django 4.2.7 on 2023-11-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_drone_createdat_alter_swarm_updatedat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='createdAT',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='swarm_id',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='updatedBy',
        ),
        migrations.RemoveField(
            model_name='swarm',
            name='UpdatedAt',
        ),
        migrations.RemoveField(
            model_name='swarm',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='swarm',
            name='createdAt',
        ),
    ]
